// Plan catalogue. Seeded into the `Plan` table — edit here (or directly in the DB)
// to change pricing; nothing in the UI hardcodes prices.
export const PLAN_CATALOG = [
  {
    key: "starter",
    name: "Starter",
    tagline: "For founders sending their first campaigns",
    monthlyPrice: 3900,
    annualPrice: 3100,
    monthlySends: 3_000,
    leadCredits: 500,
    inboxLimit: 3,
    teamMembers: 1,
    supportLevel: "Email support",
    features: ["Lead database access", "Email verification", "Unlimited sequences", "Unified inbox", "Academy access"],
    recommended: false,
    contactSales: false,
    sortOrder: 1,
  },
  {
    key: "growth",
    name: "Growth",
    tagline: "For teams building a repeatable outbound engine",
    monthlyPrice: 9900,
    annualPrice: 7900,
    monthlySends: 25_000,
    leadCredits: 5_000,
    inboxLimit: 20,
    teamMembers: 5,
    supportLevel: "Priority chat support",
    features: ["Everything in Starter", "AI personalization", "Inbox warmup", "Reply classification", "A/B testing", "API access"],
    recommended: true,
    contactSales: false,
    sortOrder: 2,
  },
  {
    key: "scale",
    name: "Scale",
    tagline: "For agencies and high-volume sales orgs",
    monthlyPrice: 24900,
    annualPrice: 19900,
    monthlySends: 100_000,
    leadCredits: 20_000,
    inboxLimit: 75,
    teamMembers: 15,
    supportLevel: "Dedicated success manager",
    features: ["Everything in Growth", "Multiple workspaces", "Advanced analytics", "Custom sending limits", "Deliverability audits"],
    recommended: false,
    contactSales: false,
    sortOrder: 3,
  },
  {
    key: "enterprise",
    name: "Enterprise",
    tagline: "Custom infrastructure, security and volume",
    monthlyPrice: 0,
    annualPrice: 0,
    monthlySends: 1_000_000,
    leadCredits: 100_000,
    inboxLimit: 500,
    teamMembers: 100,
    supportLevel: "24/7 support & SLA",
    features: ["Everything in Scale", "SSO & audit logs", "Dedicated IPs", "Custom contracts", "Onboarding & training"],
    recommended: false,
    contactSales: true,
    sortOrder: 4,
  },
];
