import type { Metadata } from "next";
import { Bot, CreditCard, Globe, Mail, MailCheck, Search } from "lucide-react";
import { db } from "@/lib/db";
import { requireWorkspace } from "@/lib/auth/guard";
import { providerStatus } from "@/lib/providers";
import { Badge } from "@/components/ui/badge";
import { Card, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export const metadata: Metadata = { title: "Integrations" };

export default async function IntegrationsPage() {
  const ctx = await requireWorkspace();
  const p = providerStatus();
  const connectedInboxes = await db.inbox.count({ where: { workspaceId: ctx.workspaceId, encryptedCredentials: { not: null } } });
  const appUrl = process.env.APP_URL ?? "http://localhost:3000";
  const publicUrl = !/localhost|127\.0\.0\.1/.test(appUrl);

  const rows = [
    {
      icon: Mail,
      title: "Email sending & reply sync",
      live: p.email.live,
      provider: p.email.live ? "Your mailboxes (SMTP + IMAP)" : "Mock (EMAIL_PROVIDER=mock)",
      detail: p.email.live
        ? `${connectedInboxes} inbox${connectedInboxes === 1 ? "" : "es"} with credentials. Emails send from each connected mailbox; replies and bounces are read back over IMAP by the worker.`
        : "Sends are simulated. Remove EMAIL_PROVIDER=mock to send for real.",
      env: ["Connect inboxes in Settings → Sending Inboxes", "Run `npm run worker` (or call /api/cron/tick)"],
    },
    {
      icon: Globe,
      title: "Open & click tracking",
      live: p.email.live && publicUrl,
      provider: publicUrl ? appUrl : "Needs a public APP_URL",
      detail: publicUrl ? "Tracking pixels and signed click links point at your deployment." : "Recipients’ mail clients can’t reach localhost, so opens/clicks won’t be recorded until APP_URL is a public https URL.",
      env: ["APP_URL=https://app.yourdomain.com"],
    },
    {
      icon: MailCheck,
      title: "Email verification",
      live: p.verification.live,
      provider: p.verification.name === "zerobounce" ? "ZeroBounce" : p.verification.name === "dns-mx" ? "Built-in DNS / MX checks" : "Mock",
      detail:
        p.verification.name === "zerobounce"
          ? "Mailbox-level verification (valid, invalid, catch-all, spam traps)."
          : p.verification.name === "dns-mx"
            ? "Real syntax, disposable-domain and MX lookups. Individual mailboxes aren’t confirmed — add ZeroBounce for that."
            : "Statuses are simulated.",
      env: ["ZEROBOUNCE_API_KEY=…"],
    },
    {
      icon: Globe,
      title: "Domain DNS checks",
      live: p.dns.live,
      provider: p.dns.live ? "Live DNS lookups" : "Mock",
      detail: "SPF, DKIM, DMARC, MX and ownership records are resolved from public DNS when you click Verify DNS.",
      env: [],
    },
    {
      icon: Search,
      title: "Lead database",
      live: p.leads.live,
      provider: p.leads.live ? "Apollo.io" : "Demo dataset",
      detail: p.leads.live ? "Search is free; revealing a lead uses Apollo enrichment credits plus 1 Leadstabo credit." : "Searches a built-in sample of ~640 prospects.",
      env: ["APOLLO_API_KEY=… (Apollo plan with API access)"],
    },
    {
      icon: CreditCard,
      title: "Payments",
      live: p.payments.live,
      provider: p.payments.live ? "Stripe Checkout" : "Test mode (instant, no charge)",
      detail: p.payments.live ? "Plans and credit packs are paid through Stripe; access is granted by the webhook." : "Plan changes and credit packs apply instantly without payment.",
      env: ["STRIPE_SECRET_KEY=sk_live_…", "STRIPE_WEBHOOK_SECRET=whsec_…", "Webhook URL: /api/webhooks/stripe"],
    },
    {
      icon: Bot,
      title: "AI writing & reply classification",
      live: p.ai.live,
      provider: p.ai.live ? "Claude (Anthropic)" : "Templates",
      detail: p.ai.live ? "Emails, rewrites, reply classification and suggested responses are generated by Claude." : "Uses built-in templates and keyword classification.",
      env: ["ANTHROPIC_API_KEY=sk-ant-…"],
    },
  ];

  return (
    <Card className="overflow-hidden">
      <CardHeader>
        <div>
          <CardTitle>Integrations</CardTitle>
          <CardDescription>Which services Leadstabo is using right now. Keys are set as server environment variables and never reach the browser.</CardDescription>
        </div>
      </CardHeader>
      <div className="divide-y border-t">
        {rows.map((r) => (
          <div key={r.title} className="grid gap-3 px-5 py-4 md:grid-cols-[1fr_280px]">
            <div className="flex gap-3">
              <span className="flex size-9 shrink-0 items-center justify-center rounded-lg border bg-muted/40">
                <r.icon className="size-4 text-muted-foreground" />
              </span>
              <div>
                <p className="flex flex-wrap items-center gap-2 text-[14px] font-medium">
                  {r.title} {r.live ? <Badge tone="success" dot>Live</Badge> : <Badge tone="warning" dot>Demo</Badge>}
                </p>
                <p className="text-[13px] text-muted-foreground">{r.provider}</p>
                <p className="mt-1 text-xs leading-5 text-muted-foreground">{r.detail}</p>
              </div>
            </div>
            {r.env.length > 0 && (
              <div className="space-y-1 self-center">
                {r.env.map((e) => (
                  <code key={e} className="block rounded border bg-muted/40 px-2 py-1 font-mono text-[11px]">
                    {e}
                  </code>
                ))}
              </div>
            )}
          </div>
        ))}
      </div>
    </Card>
  );
}
